Repository artikandri/course-scheduling-2021, pull requests merged in 2022-01, with the labels that each got.

#5 feat: produce 3 separate datasets for experiment purposes
  dataset/processed/courses_large.csv
  dataset/processed/courses_medium.csv
  dataset/processed/courses_small.csv
  src/scripts/dataset/courses_for_experiment.py
Labels: enhancement

#7 Pso full inprogress2
  ExperimentGuide.txt
  results/pso/Schedules-PSO_2022_01_11_11_56_15.txt
  results/pso/pso_full.txt
  results/pso/pso_large.txt
  results/pso/pso_medium.txt
  results/pso/pso_small.txt
  src/main/java/com/course_scheduling/app/App.java
  src/main/java/com/course_scheduling/pso/pso.java
Labels: documentation, enhancement

#8 enhancement on pso.java
  src/main/java/com/course_scheduling/pso/pso.java
Labels: enhancement

#12 fixed some bugs in GA, PSO
  .gitignore
  ExperimentGuide.txt
  src/main/java/com/course_scheduling/app/App.java
  src/main/java/com/course_scheduling/ga/Scheduler.java
  src/main/java/com/course_scheduling/pso/pso.java
Labels: documentation, enhancement

#14 fix: fixed scheduling process for the GA algorithm & fix some bugs; feat: added psoTimeLimit in pso.java; docs: updated ExperimentGuide.txt; chore: updated .gitignore, added new dependency in pom.xml
  .gitignore
  ExperimentGuide.txt
  pom.xml
  src/main/java/com/course_scheduling/app/App.java
  src/main/java/com/course_scheduling/assets/DatasetParser.java
  src/main/java/com/course_scheduling/assets/DatasetProcessor.java
  src/main/java/com/course_scheduling/ga/Data.java
  src/main/java/com/course_scheduling/ga/GeneticAlgorithm.java
  src/main/java/com/course_scheduling/ga/Penalty.java
  src/main/java/com/course_scheduling/ga/Schedule.java
  src/main/java/com/course_scheduling/ga/Scheduler.java
  src/main/java/com/course_scheduling/ga/Timeslot.java
  src/main/java/com/course_scheduling/pso/pso.java
Labels: bug, documentation, enhancement

#15 fixed bug in App.java
  src/main/java/com/course_scheduling/app/App.java
Labels: enhancement

#19 Update PSO Samples
  results/pso/Schedules-PSO_2022_01_11_11_56_15.txt
  results/pso/pso_full.txt
  results/pso/pso_large.txt
  results/pso/pso_medium.txt
  results/pso/pso_small.txt
Labels: documentation
